version: "3.3"

services:
  vesta:
    image: niiknow/vestacp
    container_name: vesta
    hostname: yourcpanelhostname.com
    volumes:
      - "/opt/vestacp/backup:/backup"
      - "/opt/vestacp/vesta:/vesta"
      - "/opt/vestacp/home:/home"
    ports:
      - "2222:22"
      - "80:80"
      - "443:443"
      - "9088:8083"
    privileged: true
    ulimits:
      nproc: 65535
      nofile:
    soft: 20000
    hard: 40000
    sysctls:
      net.core.somaxconn: '511'
    labels:
      - "Vesta Control Panel"
    restart: always

# note, set hostname for auto ssl on the panel
# also note, I set the port to 9088 above on purpose
# if you want, change it back to 8083
# it help with security to change to a different port
